version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: stockfolio_db
      POSTGRES_USER: stockfolio_user
      POSTGRES_PASSWORD: stockfolio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
