# Generated by Django 5.2.5 on 2025-08-23 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('is_etf', models.BooleanField(default=False)),
                ('tsx60_member', models.BooleanField(default=False)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('yield_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], max_length=20)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.stock')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField()),
                ('aggregate_rating', models.TextField(blank=True)),
                ('analyst_rating', models.CharField(blank=True, max_length=10)),
                ('buy_count', models.IntegerField(blank=True, null=True)),
                ('hold_count', models.IntegerField(blank=True, null=True)),
                ('sell_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_ratings', to='portfolio.stock')),
            ],
            options={
                'ordering': ['-rating_date'],
                'unique_together': {('stock', 'rating_date')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('fiftytwo_week_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiftytwo_week_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.stock')),
            ],
            options={
                'ordering': ['-price_date'],
                'unique_together': {('stock', 'price_date')},
            },
        ),
        migrations.CreateModel(
            name='ValuationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=20)),
                ('growth_3_year', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('growth_5_year', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='portfolio.stock')),
            ],
            options={
                'ordering': ['-metric_date'],
                'unique_together': {('stock', 'metric_date')},
            },
        ),
    ]
