# Generated by Django 5.2.5 on 2025-11-23 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_dividend_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='ex_dividend_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividendalert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='price_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['stock', '-ex_dividend_date'], name='portfolio_d_stock_i_c03d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['ex_dividend_date'], name='portfolio_d_ex_divi_356bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['payment_date'], name='portfolio_d_payment_ba4418_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendalert',
            index=models.Index(fields=['user', 'is_active'], name='portfolio_d_user_id_a44831_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendalert',
            index=models.Index(fields=['is_active', 'days_advance'], name='portfolio_d_is_acti_7f2d09_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='portfolio_s_sector_b22753_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol', 'sector'], name='portfolio_s_symbol_27b6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', '-price_date'], name='portfolio_s_stock_i_78a4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['-price_date'], name='portfolio_s_price_d_ec663b_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'is_active'], name='portfolio_u_user_id_3afc13_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'alert_type'], name='portfolio_u_user_id_d335f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user', 'stock'], name='portfolio_u_user_id_cc483f_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'stock'], name='portfolio_w_user_id_2f1301_idx'),
        ),
    ]
