# Generated by Django 5.2.5 on 2025-11-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_dividend_ex_dividend_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='portfolio.stock')),
            ],
            options={
                'verbose_name': 'Stock News',
                'verbose_name_plural': 'Stock News',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['stock', '-published_at'], name='portfolio_s_stock_i_ba58db_idx'), models.Index(fields=['-published_at'], name='portfolio_s_publish_1f6808_idx')],
            },
        ),
    ]
