# Generated by Django 5.2.5 on 2025-11-27 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='affiliatelink',
            new_name='portfolio_a_is_acti_daae2e_idx',
            old_name='portfolio_af_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='affiliatelink',
            new_name='portfolio_a_platfor_6f37a7_idx',
            old_name='portfolio_af_platfor_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='portfolio_e_token_80a044_idx',
            old_name='portfolio_e_token_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='portfolio_e_user_id_e95567_idx',
            old_name='portfolio_e_user_id_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliosnapshot',
            new_name='portfolio_p_user_id_b5e048_idx',
            old_name='portfolio_p_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliosnapshot',
            new_name='portfolio_p_snapsho_8bcfbc_idx',
            old_name='portfolio_p_snapsho_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapestatus',
            new_name='portfolio_s_started_f06ab8_idx',
            old_name='portfolio_s_started_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapestatus',
            new_name='portfolio_s_status_509c2a_idx',
            old_name='portfolio_s_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsoredcontent',
            new_name='portfolio_s_is_acti_3fe4b4_idx',
            old_name='portfolio_sp_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsoredcontent',
            new_name='portfolio_s_content_32deb1_idx',
            old_name='portfolio_sp_content_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsoredcontent',
            new_name='portfolio_s_start_d_1968a2_idx',
            old_name='portfolio_sp_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='stocknote',
            new_name='portfolio_s_user_id_a47ea8_idx',
            old_name='portfolio_s_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='stocknote',
            new_name='portfolio_s_stock_i_124223_idx',
            old_name='portfolio_s_stock_i_idx',
        ),
        migrations.RenameIndex(
            model_name='stocknote',
            new_name='portfolio_s_user_id_2e62fe_idx',
            old_name='portfolio_s_user_id_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='stocknote',
            new_name='portfolio_s_note_ty_e9393f_idx',
            old_name='portfolio_s_note_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_t_user_id_e385a8_idx',
            old_name='portfolio_t_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_t_user_id_f37b86_idx',
            old_name='portfolio_t_user_id_2_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_t_transac_7ab0b0_idx',
            old_name='portfolio_t_transac_idx',
        ),
        migrations.AlterField(
            model_name='stocknews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='portfolio_c_post_id_c98e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='portfolio_c_user_id_7acbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'user'], name='portfolio_c_comment_58b80e_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='portfolio_f_followe_e5250f_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='portfolio_f_followi_6e3332_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='portfolio_p_user_id_a01c93_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['stock', '-created_at'], name='portfolio_p_stock_i_aaf7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='portfolio_p_post_ty_3647d4_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='portfolio_p_post_id_a25fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='stocknews',
            index=models.Index(fields=['created_at'], name='portfolio_s_created_8a5261_idx'),
        ),
        migrations.AddIndex(
            model_name='stocknews',
            index=models.Index(fields=['stock', 'created_at'], name='portfolio_s_stock_i_5231eb_idx'),
        ),
    ]
