# Generated by Django 5.2.5 on 2025-11-28 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_rename_portfolio_af_is_acti_idx_portfolio_a_is_acti_daae2e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='portfolio_u_user_id_b45fde_idx'), models.Index(fields=['session_key'], name='portfolio_u_session_615315_idx'), models.Index(fields=['is_active', '-last_activity'], name='portfolio_u_is_acti_b102b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(db_index=True, default=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('is_mobile', models.BooleanField(db_index=True, default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Metric',
                'verbose_name_plural': 'Website Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='portfolio_w_timesta_200878_idx'), models.Index(fields=['user', '-timestamp'], name='portfolio_w_user_id_728f4a_idx'), models.Index(fields=['path', '-timestamp'], name='portfolio_w_path_63e798_idx'), models.Index(fields=['session_key', '-timestamp'], name='portfolio_w_session_ea3a0f_idx'), models.Index(fields=['is_authenticated', '-timestamp'], name='portfolio_w_is_auth_dea42f_idx'), models.Index(fields=['timestamp'], name='portfolio_w_timesta_d948aa_idx')],
            },
        ),
    ]
