# Generated by Django 5.2.5 on 2025-12-14 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_add_tags_and_watchlist_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_date', models.DateField(db_index=True)),
                ('time', models.CharField(blank=True, choices=[('bmo', 'Before Market Open'), ('amc', 'After Market Close'), ('dmh', 'During Market Hours'), ('', 'Not Specified')], max_length=10)),
                ('eps_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-earnings_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='stocktag',
            new_name='portfolio_s_user_id_0fb53a_idx',
            old_name='portfolio_s_user_id_name_idx',
        ),
        migrations.RenameIndex(
            model_name='taggedstock',
            new_name='portfolio_t_tag_id_80aa40_idx',
            old_name='portfolio_t_tag_id_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='taggedstock',
            new_name='portfolio_t_stock_i_1aed72_idx',
            old_name='portfolio_t_stock_id_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='portfolio_w_user_id_13e462_idx',
            old_name='portfolio_w_user_id_group_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlistgroup',
            new_name='portfolio_w_user_id_645828_idx',
            old_name='portfolio_w_user_id_order_idx',
        ),
        migrations.AddField(
            model_name='earnings',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='portfolio.stock'),
        ),
        migrations.AddIndex(
            model_name='earnings',
            index=models.Index(fields=['stock', '-earnings_date'], name='portfolio_e_stock_i_292c09_idx'),
        ),
        migrations.AddIndex(
            model_name='earnings',
            index=models.Index(fields=['earnings_date'], name='portfolio_e_earning_4dcddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='earnings',
            unique_together={('stock', 'earnings_date')},
        ),
    ]
