# Generated by Django 5.2.5 on 2026-04-06 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_watchlist_price_target_and_dividend_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insider_name', models.CharField(max_length=200)),
                ('insider_title', models.CharField(blank=True, max_length=200)),
                ('security_type', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('buy', 'Purchase'), ('sell', 'Sale'), ('grant', 'Grant / Award'), ('other', 'Other')], default='other', max_length=10)),
                ('nature_of_trade', models.CharField(blank=True, max_length=100)),
                ('shares', models.BigIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_balance', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('sedi_issuer_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_trades', to='portfolio.stock')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['stock', '-transaction_date'], name='portfolio_i_stock_i_8379b0_idx')],
                'unique_together': {('stock', 'insider_name', 'transaction_date', 'shares', 'transaction_type')},
            },
        ),
    ]
