# Generated by Django 5.2.5 on 2026-04-18 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_insidertrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('wealthsimple', 'Wealthsimple'), ('questrade', 'Questrade')], max_length=20)),
                ('access_token_enc', models.TextField(blank=True, default='')),
                ('refresh_token_enc', models.TextField(blank=True, default='')),
                ('otp_claim', models.CharField(blank=True, default='', max_length=500)),
                ('api_server', models.CharField(blank=True, default='', max_length=200)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('account_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['broker'],
                'unique_together': {('user', 'broker')},
            },
        ),
    ]
