# Generated by Django 5.2.5 on 2026-04-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_broker_connection'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analystrating',
            index=models.Index(fields=['stock', '-rating_date'], name='portfolio_a_stock_i_7b4a94_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationmetric',
            index=models.Index(fields=['stock', '-metric_date'], name='portfolio_v_stock_i_693c78_idx'),
        ),
    ]
