# Generated by Django 5.2.5 on 2026-06-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_add_valuation_analyst_indexes'),
    ]

    operations = [
        # view_count was added to the DB directly (without a migration) sometime earlier.
        # Record it in Django's migration state without running the SQL again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='stock',
                    name='view_count',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='stockprice',
            name='sma_200',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='sma_50',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
